import type { Metadata } from "next";
import { Cairo, IBM_Plex_Sans_Arabic } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getTranslations } from "next-intl/server";
import "./globals.css";
import { QueryProvider } from "../shared/providers/QueryProvider";
import Toaster from "../shared/components/Toaster";
import { ThemeSync } from "../shared/providers/ThemeSync";
import { themeInitScript } from "../shared/lib/theme";
import { getDirection } from "../i18n/config";

const cairo = Cairo({
  subsets: ["arabic", "latin"],
  variable: "--font-cairo",
  display: "swap",
});

const plexArabic = IBM_Plex_Sans_Arabic({
  subsets: ["arabic", "latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-plex-arabic",
  display: "swap",
});

export async function generateMetadata(): Promise<Metadata> {
  const t = await getTranslations("common.brand");
  return {
    title: t("name"),
    description: "Generated by create next app",
  };
}

export default async function RootLayout({ children }: LayoutProps<"/">) {
  // lang/dir are set during SSR from the locale cookie, so RTL never flashes.
  const locale = await getLocale();

  return (
    <html
      lang={locale}
      dir={getDirection(locale)}
      data-scroll-behavior="smooth"
      className={`${cairo.variable} ${plexArabic.variable} h-full antialiased`}
      // The theme init script adds `dark` to this element before hydration.
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body className="flex flex-col min-h-full">
        <NextIntlClientProvider>
          <ThemeSync />
          <QueryProvider>{children}</QueryProvider>
          <Toaster />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
